name: ml_models_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker_for_web: ^2.2.0
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.9
  flutter_tflite: ^1.0.1
  camera: ^0.11.0+1
  path_provider: ^2.1.3
  url_launcher: ^6.0.20
  flutter_rating_bar: ^4.0.0
  easy_dynamic_theme: ^2.2.0
  flare_flutter: ^3.0.0
  local_auth: ^2.1.3
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/instagram.png
    - assets/linkedin.png
    - assets/github.png
    - assets/credly.png
    - assets/cloud.png
    - assets/accident.png
    - assets/object.png
    - assets/emotion.png
    - assets/s.jpg
    - assets/yolov2_tiny.tflite
    - assets/yolov2_tiny.txt
    - assets/samarth.jpg
    - assets/emotion.tflite
    - assets/emotion.txt
    - assets/gender.tflite
    - assets/gender.txt

